trigger:
  branches:
    include:
      - main

stages:
  - stage: Terragrunt_Dev
    displayName: Terragrunt Dev Stage
    dependsOn: Terraform_Prod   # <-- keep/remove as needed
    condition: succeeded()
    jobs:
      - template: terragtunttemplate.yml
        parameters:
          env: dev
          workingDir: terragrunt/envs/dev

  - stage: Terragrunt_Prod
    displayName: Terragrunt Prod Stage
    dependsOn: Terragrunt_Dev
    condition: succeeded()
    jobs:
      - template: terragtunttemplate.yml
        parameters:
          env: prod
          workingDir: terragrunt/envs/prod
